### PR TITLE
Allow clarg to drop db

### PR DESCRIPTION
**Pull request by mfraezz**
start app with 
```bash
open /Applications/OSF-Offline.app --args --drop
```
to drop DB on start. `--args` tells `open` to pass `--drop` to `OSF-Offline.app`.

### CODE REVIEW

**Comment by abought** [comment]
Note for testers: this is not a feature we intend for people to use everyday. It is intended as a last-resort way for a user to reset the application (when the state of their database becomes corrupted) without them having to dig through files that they may not even be able to find.

**Comment by chennan47** [comment]
The only concern for this is that after deploy. It will be OSF-Offline.exe and based on different platform it will be running. This command will be different?

**Comment by abought** [comment]
It'll be similar, probably just omitting the word "open" (and specifying .exe instead of .app)

**Comment by abought** [comment]
Works at command line on mac, and clear from me, pending @chennan47 test on windows.

**Comment by chennan47** [comment]
Verified it works on windows deployed exe version. But the key word is "start"

**Pull request merged**
